# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Smeargle < Formula
  desc "CLI tool to print Pokémon images in the terminal"
  homepage "https://github.com/Glup3/smeargle"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Glup3/smeargle/releases/download/v0.1.0/smeargle_0.1.0_darwin_amd64.tar.gz"
      sha256 "d3539fef4e7c8a5c71d1785702b6d1e99122e3ec1a34dc74c9db64bd4bc00461"

      def install
        bin.install "smeargle"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Glup3/smeargle/releases/download/v0.1.0/smeargle_0.1.0_darwin_arm64.tar.gz"
      sha256 "1e1e4819abea7ad8135918d144e0664483ede4ab819079c8dd602b3546f5eafe"

      def install
        bin.install "smeargle"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Glup3/smeargle/releases/download/v0.1.0/smeargle_0.1.0_linux_amd64.tar.gz"
        sha256 "8839c9eae986c3b328c22e8d5f1d34ea04399771976b967b1f4c59dfb8fd816b"

        def install
          bin.install "smeargle"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Glup3/smeargle/releases/download/v0.1.0/smeargle_0.1.0_linux_arm64.tar.gz"
        sha256 "05e4f00119e14ff3d729c3e0eee9548fa0122eb8ff3c2eca721fc0ebf45d3410"

        def install
          bin.install "smeargle"
        end
      end
    end
  end
end
