# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Smeargle < Formula
  desc "CLI tool to print Pokémon images in the terminal"
  homepage "https://github.com/Glup3/smeargle"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Glup3/smeargle/releases/download/v1.0.0/smeargle_1.0.0_darwin_amd64.tar.gz"
      sha256 "f1059434c2e3f77714fe7e5825a416329b75f9fc3b8e00d6b9d64f8f8d4eec01"

      def install
        bin.install "smeargle"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Glup3/smeargle/releases/download/v1.0.0/smeargle_1.0.0_darwin_arm64.tar.gz"
      sha256 "74947c0dcaa7b745a7deab24d4a616267db65e9dc4890dfbcddeb49e5cbcc073"

      def install
        bin.install "smeargle"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Glup3/smeargle/releases/download/v1.0.0/smeargle_1.0.0_linux_amd64.tar.gz"
        sha256 "993e4f59f647c53986ec7c1402a14c4bd6cbc40c5cdd9ba0959c9075880e821a"

        def install
          bin.install "smeargle"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Glup3/smeargle/releases/download/v1.0.0/smeargle_1.0.0_linux_arm64.tar.gz"
        sha256 "548796e3d4228e63140a6b28991d4db06695c0ba1e4b0c3a418d909a0302dbbd"

        def install
          bin.install "smeargle"
        end
      end
    end
  end
end
